Бирюков, 5030102.10101
job-modelware-ru/bml-2024-tasks pull request #43
Opened 2024-12-21 14:08 UTC by Royal-Hog

2024-12-21 15:13 UTC, IlyaZawyalow requested changes
Добавьте, пожалуйста, краткую теоретическую информацию о модели, которую вы используете

2024-12-21 22:13 UTC, Royal-Hog commented
Random Forest — это ансамблевый метод машинного обучения, основанный на объединении множества решающих деревьев для решения задач классификации и регрессии. Метод основан на идее "мудрости толпы": совокупность моделей дает более надежный результат, чем отдельная модель.

1)Основные принципы работы Random Forest:
Бэггинг (Bootstrap Aggregating):
Каждый дерево в лесу обучается на случайной подвыборке данных (сэмплирование с возвращением).
Это помогает снизить переобучение, так как каждое дерево видит только часть данных.

Случайный выбор признаков:
Для построения каждого узла дерева случайным образом выбирается подмножество признаков. Это уменьшает корреляцию между деревьями и повышает устойчивость модели.

Ансамблирование:
Для классификации: итоговое предсказание основывается на голосовании деревьев (наиболее частый класс).
Для регрессии: итоговое предсказание вычисляется как среднее значение предсказаний всех деревьев.

2)Преимущества Random Forest:
Устойчивость к переобучению: За счет использования случайных подвыборок данных и признаков.
Работа с пропущенными данными: Способен справляться с неполными данными и пропусками.
Высокая точность: Обеспечивает хорошие результаты на различных задачах.
Интерпретируемость: Можно оценивать важность признаков, что полезно для анализа данных.

3)Ограничения:
Медленная предсказательная скорость: Для большого количества деревьев.
Потребление памяти: Высокие требования к памяти при большом объеме данных.

4)Основные гиперпараметры:
n_estimators: Количество деревьев в лесу.
max_depth: Максимальная глубина деревьев.
min_samples_split: Минимальное количество объектов для разбиения узла.
max_features: Количество признаков, выбираемых при разбиении.

2024-12-22 11:10 UTC, IlyaZawyalow requested changes
Добавьте эту теорию в ваш ipynb ноутбук

2024-12-22 13:54 UTC, Royal-Hog commented
Добавил

2024-12-27 19:00 UTC, merged